site_name: Django Cassiopeia
nav:
  - Home: index.md
  - Django Setup: django-setup.md
  - Avoids and DON'Ts:  cautions.md
  - Quick Starts: examples.md
  - Support and Contrib: supports.md 
theme: readthedocs

extra_css: [css/prevent-burning-your-eyes.css]